// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockStorage

import (
	contact "github.com/evgeniy-dammer/clean-architecture/internal/domain/contact"
	context "github.com/evgeniy-dammer/clean-architecture/pkg/type/context"

	mock "github.com/stretchr/testify/mock"

	queryparameter "github.com/evgeniy-dammer/clean-architecture/pkg/type/queryparameter"

	uuid "github.com/google/uuid"
)

// ContactReader is an autogenerated mock type for the ContactReader type
type ContactReader struct {
	mock.Mock
}

// CountContact provides a mock function with given fields: ctx, parameter
func (_m *ContactReader) CountContact(ctx context.Context, parameter queryparameter.QueryParameter) (uint64, error) {
	ret := _m.Called(ctx, parameter)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queryparameter.QueryParameter) (uint64, error)); ok {
		return rf(ctx, parameter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queryparameter.QueryParameter) uint64); ok {
		r0 = rf(ctx, parameter)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queryparameter.QueryParameter) error); ok {
		r1 = rf(ctx, parameter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContactByID provides a mock function with given fields: ctx, contactID
func (_m *ContactReader) GetContactByID(ctx context.Context, contactID uuid.UUID) (*contact.Contact, error) {
	ret := _m.Called(ctx, contactID)

	var r0 *contact.Contact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*contact.Contact, error)); ok {
		return rf(ctx, contactID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *contact.Contact); ok {
		r0 = rf(ctx, contactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contact.Contact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contactID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListContact provides a mock function with given fields: ctx, parameter
func (_m *ContactReader) GetListContact(ctx context.Context, parameter queryparameter.QueryParameter) ([]*contact.Contact, error) {
	ret := _m.Called(ctx, parameter)

	var r0 []*contact.Contact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queryparameter.QueryParameter) ([]*contact.Contact, error)); ok {
		return rf(ctx, parameter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queryparameter.QueryParameter) []*contact.Contact); ok {
		r0 = rf(ctx, parameter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*contact.Contact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queryparameter.QueryParameter) error); ok {
		r1 = rf(ctx, parameter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewContactReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewContactReader creates a new instance of ContactReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContactReader(t mockConstructorTestingTNewContactReader) *ContactReader {
	mock := &ContactReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
